version: "3.2"

services:
  api:
    container_name: agr.intermine.cdn.server
    image: 100225593120.dkr.ecr.us-east-1.amazonaws.com/agr_intermine_nginx_cdn:latest
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://logs.alliancegenome.org:12201'
    ports:
      - "80:80"
    networks:
      - intermine
    env_file:
      - .env

networks:
  # The presence of these objects is sufficient to define them
  intermine:
